# 手机端cookie，是pt_key=xxx;pt_pin=xxx;
cookie: ""
debug: false

# selenium 相关
# selenium.browserType: 浏览器类型
# selenium.headless: 无头模式，建议默认设置
# selenium.binary: 可执行路径，如果驱动没有找到浏览器的话需要你手动配置
# selenium.timeout: selenium操作超时时间，超过会跳过当前店铺，进行下一个店铺，默认为30秒
# selenium.check_wait: selenium操作发送验证码和校验是否成功注销的等待时间，目的是跳过黑店，默认3秒
selenium:
  browserType: "Chrome"
  headless: false
  binary: ""
  timeout: 30
  check_wait: 3

# shop 店铺设置相关
# shop.skip_shops: 需要跳过的店铺，需要填写卡包中的完整卡包名称，多个店铺用英文逗号隔开，格式为["aag会员中心", "大自然品牌会员"]
# shop.specify_shops: 指定注销的店铺，指定店铺优先级大于需要跳过的店铺，多个店铺用英文逗号隔开，格式为["aag会员中心", "大自然品牌会员"]
# shop.phone_tail_number: 手机后4位尾号，若填写将会校验店铺尾号是否是规定的，不符合就跳过，支持多手机号，格式为["0123","1234"]
# shop.member_close_max_number: 设置本次运行注销的最大店铺数，默认为0，代表不限制
# shop.wait_refresh_time: 乱码店铺挂载时间，默认为挂31分钟，可自行调整
shop:
  skip_shops: []
  specify_shops: []
  phone_tail_number: []
  member_close_max_number: 0
  wait_refresh_time: 31

# sms_captcha 短信验证码相关
# sms_captcha.is_ocr: 是否开启OCR模式，IOS设备必须开启，安卓非必须
# sms_captcha.jd_wstool: 是否调用jd_wstool工具监听验证码，默认为开启，如果不想开启，设置为false会调用内置websocket监听
# sms_captcha.ws_conn_url: websocket链接地址，不用动
# sms_captcha.ws_timeout: websocket接收验证码时间超时时间，超时会跳过当前店铺，进行下一个店铺，默认为60秒
# sms_captcha.ocr.type: ocr的类型，可选：baidu、aliyun、easyocr
# sms_captcha.ocr.ocr_range: 需要截取的投屏区域的验证码左上角和右下角坐标，顺序依次是 [左x,左y,右x,右y]，如[1,2,3,4]
# sms_captcha.ocr.ocr_delay_time: OCR识别的延迟时间，如果没识别到就几秒后再次尝试，默认为5
# sms_captcha.ocr.baidu_app_id: 百度通用文字识别应用的`app_id`
# sms_captcha.ocr.baidu_api_key: 百度通用文字识别应用的`api_key`
# sms_captcha.ocr.baidu_secret_key: 百度通用文字识别应用的`secret_key`
# sms_captcha.ocr.aliyun_appcode: 阿里云通用文字识别应用的`AppCode`
sms_captcha:
  is_ocr: false
  jd_wstool: true
  ws_conn_url: "ws://localhost:5201/subscribe"
  ws_timeout: 60
  ocr:
    type: ""
    ocr_range: [ ]
    ocr_delay_time: 10
    baidu_app_id: ""
    baidu_api_key: ""
    baidu_secret_key: ""
    aliyun_appcode: ""

# image_captcha 图形验证码相关
# image_captcha.type: 图形验证码类型，可选：local、cjy、tj、yolov4
# image_captcha.cjy_username: 超级鹰账号，仅在 image_captcha.type 为 cjy 时需要设置
# image_captcha.cjy_password: 超级鹰密码，仅在 image_captcha.type 为 cjy 时需要设置
# image_captcha.cjy_soft_id: 超级鹰软件ID，仅在 image_captcha.type 为 cjy 时需要设置
# image_captcha.cjy_kind: 超级鹰验证码类型，仅在 image_captcha.type 为 cjy 时需要设置，且该项目指定为 9101
# image_captcha.tj_username: 图鉴账号，仅在 image_captcha.type 为 tj 时需要设置
# image_captcha.tj_password: 图鉴密码，仅在 image_captcha.type 为 tj 时需要设置
# image_captcha.tj_type_id: 图鉴验证码类型，仅在 image_captcha.type 为 tj 时需要设置，且该项目指定为 19
# yolov4_weights: yolov4权重文件路径，仅在 image_captcha.type 为 yolov4 时需要设置
# yolov4_cfg: yolov4配置文件路径，仅在 image_captcha.type 为 yolov4 时需要设置
# yolov4_net_size: yolov4网络size，仅在 image_captcha.type 为 yolov4 时需要设置
image_captcha:
  type: "yolov4"
  cjy_username: ""
  cjy_password: ""
  cjy_soft_id: ""
  cjy_kind: 9101
  tj_username: ""
  tj_password: ""
  tj_type_id: 19
  yolov4_weights: "yolov4/yolov4-tiny-custom.weights"
  yolov4_cfg: "yolov4/yolov4-tiny-custom.cfg"
  yolov4_net_size: 512

# user-agent 用户代理，可自行配置
user-agent:
  - Mozilla/5.0 (Linux; Android 11; M2007J3SC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36
  - okhttp/3.12.1;jdmall;android;version/10.0.2;build/88569;screen/1080x2266;os/11;network/wifi;